#!/usr/bin/env node
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { z } from 'zod'
import { registry } from '../src/tools/registry.js'
import type { AnyToolDef, Ctx, RequestSpec } from '../src/tools/types.js'

/**
 * Emit `docs/tools.md` from the registry.
 *
 * A hand-maintained table of fifty tools goes stale in one release and then
 * silently lies about what is installed, so the published list is generated and
 * CI fails if regenerating produces a diff.
 *
 * Method and path are not declared on `ToolDef` — they live inside each
 * handler. Rather than duplicate them into fifty definitions, each handler is
 * invoked against a recording transport with placeholder arguments named after
 * the arguments themselves. A tool taking `service` is called with the literal
 * string `{service}`, so the recorded path comes out as
 * `/v2/service/{service}/dns/record` — the template a reader wants, derived
 * rather than transcribed.
 *
 * Run with `npm run docs:tools`.
 */

const OUT = fileURLToPath(new URL('../docs/tools.md', import.meta.url))

interface JsonSchema {
  properties?: Record<string, JsonSchemaProperty>
  required?: string[]
}

interface JsonSchemaProperty {
  type?: string
  const?: unknown
  enum?: unknown[]
  default?: unknown
}

/**
 * A value that satisfies the schema and reads as a placeholder in a path.
 * Named after the field, so `hostingId` renders as `{hostingId}`.
 */
function placeholder(name: string, property: JsonSchemaProperty): unknown {
  if (property.const !== undefined) return property.const
  if (property.enum?.length) return property.enum[0]
  switch (property.type) {
    case 'number':
    case 'integer':
      return 1
    case 'boolean':
      return true
    case 'array':
      return []
    default:
      return `{${name}}`
  }
}

function placeholderInput(tool: AnyToolDef): Record<string, unknown> {
  const schema = z.toJSONSchema(tool.inputSchema, { io: 'input' }) as JsonSchema
  const input: Record<string, unknown> = {}
  for (const name of schema.required ?? []) {
    const property = schema.properties?.[name]
    if (property) input[name] = placeholder(name, property)
  }
  return input
}

/** Run the handler far enough to record the request it would have made. */
async function routeOf(tool: AnyToolDef): Promise<string> {
  let recorded: RequestSpec | undefined
  const ctx: Ctx = {
    request: async (spec) => {
      recorded ??= spec
      // Enough shape for a create handler to survive its follow-up re-list.
      return { status: 200, body: { data: [], items: [] } } as never
    },
  }

  try {
    await tool.handler(tool.inputSchema.parse(placeholderInput(tool)), ctx)
  } catch {
    // A handler may still throw after issuing its first request; the recorded
    // spec is what matters.
  }

  if (!recorded) return '_not derivable_'
  // The path builders percent-encode path segments, which turns the `{name}`
  // placeholders into `%7Bname%7D`. Restore them so the table reads as a
  // template rather than as an escaped URL.
  const path = recorded.path.replaceAll('%7B', '{').replaceAll('%7D', '}')
  return `\`${recorded.method}\` \`${path}\``
}

function declaresConfirm(tool: AnyToolDef): boolean {
  const schema = z.toJSONSchema(tool.inputSchema, { io: 'input' }) as JsonSchema
  return Boolean(schema.properties && 'confirm' in schema.properties)
}

/** First sentence only — the table needs a summary, not the full description. */
function summarise(description: string): string {
  const sentence = description.split(/(?<=\.)\s/)[0] ?? description
  return sentence.replace(/\|/g, '\\|')
}

const TIER_ORDER = ['read', 'write', 'destructive'] as const

const TIER_BLURB: Record<string, string> = {
  read: 'Always registered. No environment opt-in required.',
  write: 'Registered only when `WEBSUPPORT_ALLOW_WRITE=1`.',
  destructive:
    'Registered only when `WEBSUPPORT_ALLOW_DESTRUCTIVE=1`, **and** every call must pass `confirm: true`.',
}

async function main(): Promise<void> {
  const rows = await Promise.all(
    registry.map(async (tool) => ({
      name: tool.name,
      tier: tool.tier,
      route: await routeOf(tool),
      confirm: declaresConfirm(tool),
      summary: summarise(tool.description),
    })),
  )

  const lines: string[] = [
    '<!-- Generated by scripts/generate-tools-doc.ts. Do not edit by hand. -->',
    '',
    '# Tools',
    '',
    `${rows.length} tools. Tiers gate **registration**, not just execution — a tool whose tier is not`,
    'enabled never appears in `tools/list` at all, so it costs the client no context and offers no',
    'affordance.',
    '',
    '| Tier | Tools | Opt-in |',
    '| --- | --- | --- |',
  ]

  for (const tier of TIER_ORDER) {
    const count = rows.filter((r) => r.tier === tier).length
    lines.push(`| \`${tier}\` | ${count} | ${TIER_BLURB[tier]} |`)
  }

  for (const tier of TIER_ORDER) {
    const group = rows.filter((r) => r.tier === tier)
    if (group.length === 0) continue
    lines.push('', `## \`${tier}\``, '', TIER_BLURB[tier] ?? '', '')
    lines.push('| Tool | Method + path | Confirm | Summary |', '| --- | --- | --- | --- |')
    for (const r of group) {
      lines.push(`| \`${r.name}\` | ${r.route} | ${r.confirm ? 'required' : '—'} | ${r.summary} |`)
    }
  }

  lines.push('')
  writeFileSync(OUT, lines.join('\n'))
  console.error(`wrote ${OUT} — ${rows.length} tools`)
}

await main()
